### ISSUE TITLE
Broken template on Safari (OSx)

### ISSUE THREAD

**Issue by mmornati** [ktweeden/whatisclocks#2]
The theme it is not working (at all) on Safari browser (it is working good on Chrome).

![schermata 2016-06-05 alle 20 49 31](https://cloud.githubusercontent.com/assets/139323/15807458/28577a3e-2b5f-11e6-8e1a-585221391dc9.png)

**Comment by artiepreston** [comment]
Goodness, that's pretty bad. I'll take a look today!

**Comment by artiepreston** [comment]
Ok, this should be fixed now in 2be1718 

Thanks for pointing this out!
