### ISSUE TITLE
numbered bullets appear as circle

### ISSUE THREAD

**Issue by pubmania** [ktweeden/whatisclocks#4]
Hi,

Numbered bullets and footnotes appear as circles in this theme. I tried messing around with the post.css but it did not help. Please can you let me know how can I make the theme to differentiate between un-ordered and ordered lists.

eg: 
1. AAA
2. BBB
3. CCC

 is displayed as 

* AAA
* BBB
* CCC

**Comment by artiepreston** [comment]
Hey @pubmania ,

Thanks for letting me know - I'll take a look tonight and see if I can sort it out :)

Kate

**Comment by pubmania** [comment]
Thanks :)

**Comment by pubmania** [comment]
Hi just wondering if you had a chance to look at this and if you could guide me on how I can resolve this problem.

**Comment by artiepreston** [comment]
Hi @pubmania 
Sorry about the delay - this issue should be all fixed now :)

Kate

**Comment by pubmania** [comment]
Thanks. I can confirm that the issue is now fixed.
